// Code generated by MockGen. DO NOT EDIT.
// Source: breakglasscredential_client.go
//
// Generated by this command:
//
//	mockgen -source=breakglasscredential_client.go -package=test -destination=test/mock_breakglasscredential_client.go
//
// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	client "github.com/openshift-online/ocm-common/pkg/ocm/client"
	v1 "github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockBreakGlassCredentialClient is a mock of BreakGlassCredentialClient interface.
type MockBreakGlassCredentialClient struct {
	ctrl     *gomock.Controller
	recorder *MockBreakGlassCredentialClientMockRecorder
}

// MockBreakGlassCredentialClientMockRecorder is the mock recorder for MockBreakGlassCredentialClient.
type MockBreakGlassCredentialClientMockRecorder struct {
	mock *MockBreakGlassCredentialClient
}

// NewMockBreakGlassCredentialClient creates a new mock instance.
func NewMockBreakGlassCredentialClient(ctrl *gomock.Controller) *MockBreakGlassCredentialClient {
	mock := &MockBreakGlassCredentialClient{ctrl: ctrl}
	mock.recorder = &MockBreakGlassCredentialClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBreakGlassCredentialClient) EXPECT() *MockBreakGlassCredentialClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBreakGlassCredentialClient) Create(ctx context.Context, clusterId string, instance *v1.BreakGlassCredential) (*v1.BreakGlassCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, clusterId, instance)
	ret0, _ := ret[0].(*v1.BreakGlassCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBreakGlassCredentialClientMockRecorder) Create(ctx, clusterId, instance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBreakGlassCredentialClient)(nil).Create), ctx, clusterId, instance)
}

// Delete mocks base method.
func (m *MockBreakGlassCredentialClient) Delete(ctx context.Context, clusterId, instanceId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, clusterId, instanceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBreakGlassCredentialClientMockRecorder) Delete(ctx, clusterId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBreakGlassCredentialClient)(nil).Delete), ctx, clusterId, instanceId)
}

// Exists mocks base method.
func (m *MockBreakGlassCredentialClient) Exists(ctx context.Context, clusterId, instanceId string) (bool, *v1.BreakGlassCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, clusterId, instanceId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*v1.BreakGlassCredential)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Exists indicates an expected call of Exists.
func (mr *MockBreakGlassCredentialClientMockRecorder) Exists(ctx, clusterId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockBreakGlassCredentialClient)(nil).Exists), ctx, clusterId, instanceId)
}

// Get mocks base method.
func (m *MockBreakGlassCredentialClient) Get(ctx context.Context, clusterId, instanceId string) (*v1.BreakGlassCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, clusterId, instanceId)
	ret0, _ := ret[0].(*v1.BreakGlassCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBreakGlassCredentialClientMockRecorder) Get(ctx, clusterId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBreakGlassCredentialClient)(nil).Get), ctx, clusterId, instanceId)
}

// List mocks base method.
func (m *MockBreakGlassCredentialClient) List(ctx context.Context, clusterId string, paging client.Paging) ([]*v1.BreakGlassCredential, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, clusterId, paging)
	ret0, _ := ret[0].([]*v1.BreakGlassCredential)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockBreakGlassCredentialClientMockRecorder) List(ctx, clusterId, paging any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBreakGlassCredentialClient)(nil).List), ctx, clusterId, paging)
}

// Update mocks base method.
func (m *MockBreakGlassCredentialClient) Update(ctx context.Context, clusterId string, instance *v1.BreakGlassCredential) (*v1.BreakGlassCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, clusterId, instance)
	ret0, _ := ret[0].(*v1.BreakGlassCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBreakGlassCredentialClientMockRecorder) Update(ctx, clusterId, instance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBreakGlassCredentialClient)(nil).Update), ctx, clusterId, instance)
}
